# Generated by Django 2.1.2 on 2018-11-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('HouseSearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
