# Generated by Django 2.1.2 on 2018-11-02 17:58

import HouseSearch.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('HouseSearch', '0003_auto_20181102_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='country',
            field=models.ForeignKey(on_delete=models.SET(HouseSearch.models.get_sentinel_country),
                                    to='UserProfile.Country'),
        ),
    ]
