# Generated by Django 2.1.2 on 2018-11-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('HouseSearch', '0004_auto_20181102_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housephoto',
            old_name='photo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='house',
            name='deleted',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
