# Generated by Django 2.1.1 on 2018-09-27 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('TR', 'В путешествии'), ('SH', 'Ищу жильё'), ('HH', 'Сдаю жильё')], default='TR', max_length=2)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('birthday', models.DateField()),
                ('info', models.TextField(blank=True, max_length=256)),
                ('registration', models.DateField(auto_now_add=True)),
                ('last_visit', models.DateTimeField()),
                ('big_photo', models.ImageField(upload_to='user_photo/')),
                ('user', models.OneToOneField(on_delete='Cascade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
