# Generated by Django 2.1.1 on 2018-09-29 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IM', 'фото'), ('VD', 'видео'), ('AU', 'аудио'), ('FL', 'файл')], max_length=2)),
                ('file', models.FileField(upload_to='user_files/<django.db.models.fields.CharField>/')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1000)),
                ('date_public', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete='Cascade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='big_photo',
            field=models.ImageField(blank=True, upload_to='user_photo/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='last_visit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='note',
            field=models.ForeignKey(on_delete='Cascade', to='UserProfile.Note'),
        ),
    ]
