# Generated by Django 2.1.2 on 2018-10-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_auto_20180929_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone_num',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='status',
            field=models.CharField(blank=True, choices=[('TR', 'Travelling'), ('SH', 'Find house'), ('HH', 'Rent a house')], default='TR', max_length=2),
        ),
    ]
