# Generated by Django 2.1.2 on 2018-10-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserProfile', '0003_auto_20181007_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='big_photo',
            field=models.ImageField(blank=True, default='user_photo/def_user_photo.png', upload_to='user_photo/'),
        ),
    ]
