# Generated by Django 2.1.2 on 2018-10-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserProfile', '0004_auto_20181015_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='big_photo',
            field=models.ImageField(blank=True, default='def_user_photo.png', upload_to='user_photo/'),
        ),
    ]
