# Generated by Django 2.1.2 on 2018-10-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserProfile', '0005_auto_20181015_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, upload_to='user_files/img/'),
        ),
    ]
