# Generated by Django 2.1.2 on 2018-10-26 21:17

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('UserProfile', '0006_auto_20181021_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExt',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='note',
            managers=[
                ('note_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='deleted',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, upload_to='user_files/all_files/'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.CharField(choices=[('IM', 'images'), ('VD', 'video'), ('AU', 'audio'), ('FL', 'files')],
                                   max_length=2),
        ),
    ]
