# Generated by Django 2.1 on 2018-11-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0007_auto_20181026_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_code', models.CharField(max_length=4)),
            ],
        ),
        migrations.AlterModelManagers(
            name='note',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='country',
            field=models.ForeignKey(null=True, on_delete='Cascade', to='UserProfile.Country'),
        ),
    ]
